GCR ?= 
tag ?= latest
service ?= poke-service

activate:
	@gcloud config configurations activate kadima
	@gcloud auth application-default login

activate.veed: 
	@gcloud config configurations activate veed
	@gcloud auth application-default login
